name: testflow
createdAt: 24-05-01 16:27:00
nodes:
  - 1: User,user
  - 2: Username,username
  - 3: Phone,phone
  - 4: Customer,customer
  - 5: Product,product
  - 6: Order,order
  - 7: Purchase,purchase
flow: 
  - 1>>2,3
  - 2,3>>4
  - 4,5>>6
  - 6>>7
inputs:
  - User: 
      name: John Doe
      phone: 123-456-7890
      email: john.doe@gmail.com
  - Product:
      product: beer
      price: 10

